package com.ovan.camera;
import android.Manifest;import android.content.ContentValues;import android.content.pm.PackageManager;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.graphics.ImageFormat;import android.os.Build;import android.os.Bundle;import android.provider.MediaStore;import android.view.View;import android.widget.*;import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;import com.google.common.util.concurrent.ListenableFuture;import java.io.*;import java.nio.ByteBuffer;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends AppCompatActivity{
 PreviewView preview;ImageCapture capture;Camera camera;CameraSelector selector=CameraSelector.DEFAULT_BACK_CAMERA;boolean night=true,busy=false,torch=false;TextView status;Button torchBtn;List<byte[]> frames=new ArrayList<>();ExecutorService exec=Executors.newSingleThreadExecutor();
 ActivityResultLauncher<String[]> perms=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->startCamera());
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);preview=findViewById(R.id.preview);status=findViewById(R.id.statusText);torchBtn=findViewById(R.id.torchButton);findViewById(R.id.captureButton).setOnClickListener(v->take());findViewById(R.id.captureInner).setOnClickListener(v->take());findViewById(R.id.switchButton).setOnClickListener(v->{selector=selector==CameraSelector.DEFAULT_BACK_CAMERA?CameraSelector.DEFAULT_FRONT_CAMERA:CameraSelector.DEFAULT_BACK_CAMERA;startCamera();});torchBtn.setOnClickListener(v->{torch=!torch;applyTorch();});findViewById(R.id.photoMode).setOnClickListener(v->{night=false;Toast.makeText(this,"PHOTO aktif",Toast.LENGTH_SHORT).show();});findViewById(R.id.nightMode).setOnClickListener(v->{night=true;Toast.makeText(this,"NIGHT SIGHT aktif — 5 frame",Toast.LENGTH_SHORT).show();});findViewById(R.id.portraitMode).setOnClickListener(v->Toast.makeText(this,"Portrait mode dasar CameraX",Toast.LENGTH_SHORT).show());findViewById(R.id.videoMode).setOnClickListener(v->Toast.makeText(this,"Video mode belum diaktifkan",Toast.LENGTH_SHORT).show());if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)perms.launch(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO});else startCamera();}
 void startCamera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();p.unbindAll();Preview pr=new Preview.Builder().build();capture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).build();camera=p.bindToLifecycle(this,selector,pr,capture);pr.setSurfaceProvider(preview.getSurfaceProvider());applyTorch();}catch(Exception e){Toast.makeText(this,"Kamera gagal dibuka",Toast.LENGTH_LONG).show();}},ContextCompat.getMainExecutor(this));}
 void applyTorch(){if(camera!=null&&camera.getCameraInfo().hasFlashUnit()){camera.getCameraControl().enableTorch(torch);torchBtn.setText(torch?"Flash ON":"Flash");}}
 void take(){if(busy||capture==null)return;if(!night){single();return;}busy=true;frames.clear();status.setVisibility(View.VISIBLE);nightFrame(0);}
 void single(){capture.takePicture(exec,new ImageCapture.OnImageCapturedCallback(){public void onCaptureSuccess(@NonNull ImageProxy i){byte[] d=jpeg(i);i.close();if(d!=null)save(d,"OVAN");}public void onError(@NonNull ImageCaptureException e){Toast.makeText(MainActivity.this,"Gagal mengambil foto",Toast.LENGTH_SHORT).show();}});}
 void nightFrame(int n){runOnUiThread(()->status.setText("NIGHT SIGHT • frame "+(n+1)+"/5"));capture.takePicture(exec,new ImageCapture.OnImageCapturedCallback(){public void onCaptureSuccess(@NonNull ImageProxy i){byte[] d=jpeg(i);i.close();if(d!=null)frames.add(d);if(n<4){try{Thread.sleep(90);}catch(Exception ignored){}nightFrame(n+1);}else{save(merge(frames),"OVAN_NIGHT");busy=false;runOnUiThread(()->status.setVisibility(View.GONE));}}public void onError(@NonNull ImageCaptureException e){busy=false;runOnUiThread(()->status.setVisibility(View.GONE));}});}
 byte[] jpeg(ImageProxy i){if(i.getFormat()!=ImageFormat.JPEG)return null;ByteBuffer b=i.getPlanes()[0].getBuffer();byte[] d=new byte[b.remaining()];b.get(d);return d;}
 byte[] merge(List<byte[]> a){if(a.isEmpty())return null;Bitmap base=BitmapFactory.decodeByteArray(a.get(0),0,a.get(0).length);if(base==null)return a.get(0);int w=base.getWidth(),h=base.getHeight();long[] s=new long[w*h*3];int c=0;for(byte[] d:a){Bitmap b=BitmapFactory.decodeByteArray(d,0,d.length);if(b==null||b.getWidth()!=w||b.getHeight()!=h)continue;int[] px=new int[w*h];b.getPixels(px,0,w,0,0,w,h);for(int i=0;i<px.length;i++){int x=px[i];s[i*3]+=(x>>16)&255;s[i*3+1]+=(x>>8)&255;s[i*3+2]+=x&255;}c++;b.recycle();}if(c==0)return a.get(0);Bitmap out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);int[] px=new int[w*h];for(int i=0;i<px.length;i++)px[i]=0xff000000|((int)(s[i*3]/c)<<16)|((int)(s[i*3+1]/c)<<8)|(int)(s[i*3+2]/c);out.setPixels(px,0,w,0,0,w,h);ByteArrayOutputStream o=new ByteArrayOutputStream();out.compress(Bitmap.CompressFormat.JPEG,96,o);out.recycle();return o.toByteArray();}
 void save(byte[] d,String pre){if(d==null)return;try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,pre+"_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/OVAN Camera");OutputStream o=getContentResolver().openOutputStream(getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v));o.write(d);o.close();runOnUiThread(()->Toast.makeText(this,"Foto tersimpan di Pictures/OVAN Camera",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Gagal menyimpan foto",Toast.LENGTH_SHORT).show());}}
 @Override protected void onDestroy(){super.onDestroy();exec.shutdown();}
}
