package com.ovan.camera;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.annotation.*;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;import java.io.*;import java.nio.*;import java.text.*;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends AppCompatActivity{
 PreviewView preview; ImageCapture capture; Camera camera; CameraSelector selector=CameraSelector.DEFAULT_BACK_CAMERA; boolean night=true,busy=false,torch=false; TextView status; Button flash; ExecutorService ex=Executors.newSingleThreadExecutor(); ArrayList<byte[]> frames=new ArrayList<>();
 ActivityResultLauncher<String[]> perms=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->startCamera());
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);preview=findViewById(R.id.preview);status=findViewById(R.id.statusText);flash=findViewById(R.id.torchButton);findViewById(R.id.captureButton).setOnClickListener(v->take());findViewById(R.id.captureInner).setOnClickListener(v->take());findViewById(R.id.switchButton).setOnClickListener(v->{selector=selector==CameraSelector.DEFAULT_BACK_CAMERA?CameraSelector.DEFAULT_FRONT_CAMERA:CameraSelector.DEFAULT_BACK_CAMERA;startCamera();});flash.setOnClickListener(v->{torch=!torch;applyTorch();});findViewById(R.id.photoMode).setOnClickListener(v->{night=false;toast("PHOTO aktif");});findViewById(R.id.nightMode).setOnClickListener(v->{night=true;toast("NIGHT SIGHT aktif — 5 frame");});if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)perms.launch(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO});else startCamera();}
 void startCamera(){ProcessCameraProvider.getInstance(this).addListener(()->{try{ProcessCameraProvider p=ProcessCameraProvider.getInstance(this).get();p.unbindAll();Preview pr=new Preview.Builder().build();capture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).build();camera=p.bindToLifecycle(this,selector,pr,capture);pr.setSurfaceProvider(preview.getSurfaceProvider());applyTorch();}catch(Exception e){toast("Kamera gagal dibuka");}},ContextCompat.getMainExecutor(this));}
 void applyTorch(){if(camera!=null&&camera.getCameraInfo().hasFlashUnit()){camera.getCameraControl().enableTorch(torch);flash.setText(torch?"Flash ON":"Flash");}}
 void take(){if(busy||capture==null)return;if(!night){single();return;}busy=true;frames.clear();status.setVisibility(View.VISIBLE);frame(0);}
 void single(){capture.takePicture(ex,new ImageCapture.OnImageCapturedCallback(){public void onCaptureSuccess(@NonNull ImageProxy i){byte[] d=jpeg(i);i.close();save(d,"OVAN");}public void onError(@NonNull ImageCaptureException e){toast("Gagal mengambil foto");}});}
 void frame(final int n){runOnUiThread(()->status.setText("NIGHT SIGHT • frame "+(n+1)+"/5"));capture.takePicture(ex,new ImageCapture.OnImageCapturedCallback(){public void onCaptureSuccess(@NonNull ImageProxy i){byte[] d=jpeg(i);i.close();if(d!=null)frames.add(d);if(n<4){try{Thread.sleep(90);}catch(Exception ignored){}frame(n+1);}else{save(merge(frames),"OVAN_NIGHT");busy=false;runOnUiThread(()->status.setVisibility(View.GONE));}}public void onError(@NonNull ImageCaptureException e){busy=false;runOnUiThread(()->status.setVisibility(View.GONE));toast("Night Sight gagal");}});}
 byte[] jpeg(ImageProxy i){if(i.getFormat()!=ImageFormat.JPEG)return null;ByteBuffer b=i.getPlanes()[0].getBuffer();byte[] d=new byte[b.remaining()];b.get(d);return d;}
 byte[] merge(ArrayList<byte[]> a){if(a.isEmpty())return null;Bitmap base=BitmapFactory.decodeByteArray(a.get(0),0,a.get(0).length);if(base==null)return a.get(0);int w=base.getWidth(),h=base.getHeight(),N=w*h;long[] s=new long[N*3];int c=0;for(byte[] d:a){Bitmap b=BitmapFactory.decodeByteArray(d,0,d.length);if(b==null||b.getWidth()!=w||b.getHeight()!=h)continue;int[] p=new int[N];b.getPixels(p,0,w,0,0,w,h);for(int k=0;k<N;k++){int x=p[k];s[k*3]+=(x>>16)&255;s[k*3+1]+=(x>>8)&255;s[k*3+2]+=x&255;}c++;b.recycle();}if(c==0)return a.get(0);Bitmap o=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);int[] p=new int[N];for(int k=0;k<N;k++){int r=(int)(s[k*3]/c),g=(int)(s[k*3+1]/c),bb=(int)(s[k*3+2]/c);p[k]=0xff000000|(r<<16)|(g<<8)|bb;}o.setPixels(p,0,w,0,0,w,h);ByteArrayOutputStream os=new ByteArrayOutputStream();o.compress(Bitmap.CompressFormat.JPEG,96,os);o.recycle();return os.toByteArray();}
 void save(byte[] d,String pre){if(d==null)return;String n=pre+"_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".jpg";try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,n);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/OVAN Camera");android.net.Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u!=null){OutputStream o=getContentResolver().openOutputStream(u);o.write(d);o.close();toast("Foto tersimpan di Pictures/OVAN Camera");}}catch(Exception e){toast("Gagal menyimpan foto");}}
 void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());} protected void onDestroy(){super.onDestroy();ex.shutdown();}
}
