plugins { id 'com.android.application' }
android { namespace 'com.ovan.camera'; compileSdk 35
 defaultConfig { applicationId 'com.ovan.camera'; minSdk 21; targetSdk 35; versionCode 430; versionName '4.3.0' }
}
dependencies {
 implementation 'androidx.appcompat:appcompat:1.7.0'
 implementation 'androidx.activity:activity:1.10.1'
 implementation 'androidx.camera:camera-core:1.4.2'
 implementation 'androidx.camera:camera-camera2:1.4.2'
 implementation 'androidx.camera:camera-lifecycle:1.4.2'
 implementation 'androidx.camera:camera-view:1.4.2'
}
